version: "3.9"

services:
  web:
    build: .
    entrypoint: /entrypoint.sh
    restart: on-failure:10
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - dbdata:/var/lib/mysql/
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/mysql/
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10

  celery:
    restart: always
    build:
      context: .
    command: ['celery', '-A', 'library', 'worker', '-l', 'info']
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/mysql/
    depends_on:
      - web
      - redis

  redis:
    restart: unless-stopped
    image: redis:latest
    env_file:
      - ./.env
    expose:
      - "${REDIS_PORT}"

volumes:
  dbdata: